{{- $autoscalingEnabled := true -}}
{{- if eq (.Values.autoscaling).enabled false -}}
{{- $autoscalingEnabled = .Values.autoscaling.enabled -}}
{{- end -}}

{{- $minReplicas := 1 -}}
{{- if ((.Values.autoscaling).minReplicas) }}
{{- $minReplicas = .Values.autoscaling.minReplicas }}
{{- end }}

{{- $maxReplicas := 10 -}}
{{- if ((.Values.autoscaling).maxReplicas) }}
{{- $maxReplicas = .Values.autoscaling.maxReplicas }}
{{- end }}

{{- $targetCPUUtilizationPercentage := 70 -}}
{{- if ((.Values.autoscaling).targetCPUUtilizationPercentage) }}
{{- $targetCPUUtilizationPercentage = .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

{{- if $autoscalingEnabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mainsinergija22.fullname" . }}
  labels:
    {{- include "mainsinergija22.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mainsinergija22.fullname" . }}
  minReplicas: {{ $minReplicas }}
  maxReplicas: {{ $maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $targetCPUUtilizationPercentage }}
    {{- if ((.Values.autoscaling).targetMemoryUtilizationPercentage) }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
