{{- $tenantId := "d7dedc1c-5e28-4c3b-a173-fe24b1923684" -}}
{{- if (.Values.tenantId) }}
{{- $tenantId = .Values.tenantId }}
{{- end }}

{{- $secretsName :=  printf "kv-%s-%s" .Values.service.name .Values.service.projectName -}}
{{- if ((.Values.secrets).name) }}
{{- $secretsName = .Values.secrets.name }}
{{- end }}

{{- $keyvaultName := printf "kv-%s-%s-%s" .Values.service.name .Values.service.projectName .Values.service.env -}}
{{- if ((.Values.secrets).keyvaultName) }}
{{- $keyvaultName = .Values.secrets.keyvaultName }}
{{- end }}

{{- $serviceNameTitle := title (.Values.service.name) }}

# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $secretsName }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.secrets.identity }} # Set the clientID of the user-assigned managed identity to use
    keyvaultName: {{ $keyvaultName }} # Set to the name of your key vault
    objects: |
      {{- with .Values.pod.env }}
      array:
        {{- if .useServiceDatabase -}}
        {{ indent 14 ""}}
        - |
          objectName: "ConnectionStrings--{{ $serviceNameTitle }}Db"
          objectType: secret
        {{- end }}

        {{- if .useStorageBlob -}}
        {{ indent 14 ""}}
        - |
          objectName: "ConnectionStrings--StorageAccount--Blob"
          objectType: secret
        {{- end }}

        {{- if .userStorageQueue -}}
        {{ indent 14 ""}}
        - |
          objectName: "ConnectionStrings--StorageAccount--Queue"
          objectType: secret
        {{- end }}
      {{- end }}
    tenantId: {{ $tenantId }} # The tenant ID of the key vault
  secretObjects:
    - secretName: {{ $secretsName }}
      data:
        {{- with .Values.pod.env }}
        {{- if .useServiceDatabase -}}
        {{ indent 14 ""}}
        - key: "ConnectionStrings--{{ $serviceNameTitle }}Db"
          objectName: "ConnectionStrings--{{ $serviceNameTitle }}Db"
        {{- end }}
        {{- if .useStorageBlob -}}
        {{ indent 14 ""}}
        - key: ConnectionStrings--StorageAccount--Blob
          objectName: "ConnectionStrings--StorageAccount--Blob"
        {{- end }}
        {{- if .userStorageQueue -}}
        {{ indent 14 ""}}
        - key: ConnectionStrings--StorageAccount--Queue
          objectName: "ConnectionStrings--StorageAccount--Queue"
        {{- end }}

        {{- if .customValues -}}
        {{- range .customValues }}
        - key: {{ .name }}
        {{- with .valueFrom -}}
        {{ indent 14 ""}}
          objectName: {{ toYaml .secretKeyRef.key | nindent 16 }}
        {{- end }}
        {{- end }}
        {{- end }}
        
        {{- end }}

        
      type: Opaque
