{{- $tenantId := "d7dedc1c-5e28-4c3b-a173-fe24b1923684" -}}
{{- if (.Values.tenantId) }}
{{- $tenantId = .Values.tenantId }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mainsinergija22.serviceAccountName" . }}
  labels:
    {{- include "mainsinergija22.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId }}
    azure.workload.identity/tenant-id: {{ $tenantId }}