service:
  name: simple
  projectName: sin22v3
  env: dev

image:
  repository: crsin22v3dev.azurecr.io/simple

serviceAccount:
  clientId: 903eb56c-b5ca-4835-b148-ff6dd9f96db5

secrets:
  identity: 9a83055e-4462-4802-a784-2335327fccab

pod:
  env:
    useServiceDatabase: false
    useStorageBlob: true
    userStorageQueue: false

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false


